name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to EKS
      uses: aws-actions/amazon-eks-deploy@v1
      with:
        cluster-name: cyber-api-cluster
        manifest-file: infrastructure/k8s/**/*.yaml