apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: worker
        image: 371601828313.dkr.ecr.ap-south-1.amazonaws.com/smkpie-runtime:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: api-config
        - secretRef:
            name: api-secrets
        command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]